######################################################################
# Automatically generated by qmake (2.01a) Sat Apr 25 19:03:24 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
